# Generated by Django 5.1.7 on 2025-03-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_image',
            field=models.ImageField(blank=True, upload_to='photos/products/variation'),
        ),
    ]
