# Generated by Django 5.1.7 on 2026-06-01 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0009_recommendation_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
