# Generated by Django 5.1.7 on 2026-06-01 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="redemption",
            new_name="coupons_red_coupon__75a818_idx",
            old_name="coupons_red_coupon__c8e8e5_idx",
        ),
        migrations.RenameIndex(
            model_name="redemption",
            new_name="coupons_red_coupon__0299a9_idx",
            old_name="coupons_red_coupon__7f8a9b_idx",
        ),
    ]
