"""
Django settings for greatkartecommerce project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import logging
from configurations import Configuration, values
from django.contrib.messages import constants as messages
from decouple import config
try:
    from celery.schedules import crontab
except Exception:  # pragma: no cover
    def crontab(*args, **kwargs):
        return None
try:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
except Exception:  # pragma: no cover
    sentry_sdk = None
    DjangoIntegration = None



class Dev(Configuration):

        # Build paths inside the project like this: BASE_DIR / 'subdir'.
        BASE_DIR = Path(__file__).resolve().parent.parent


        # Quick-start development settings - unsuitable for production
        # See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

        # SECURITY WARNING: keep the secret key used in production secret!
        SECRET_KEY = config('SECRET_KEY')

        # SECURITY WARNING: don't run with debug turned on in production!
        DEBUG = config('DEBUG', default=False, cast=bool)

        ALLOWED_HOSTS = []


        # Application definition

        INSTALLED_APPS = [
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            'greatkart',
            'category',
            'accounts',
            'store',
            'carts',
            'orders',
            'coupons',
            'recommendations',
            'wishlist',
            'filters',
            'inventory_alerts',
            'addresses',
            'comparison',
            'admin_honeypot',  # Honeypot for admin login
           
        ]

        MIDDLEWARE = [
            'django.middleware.security.SecurityMiddleware',
            'greatkartecommerce.security.CSPMiddleware',
            'greatkartecommerce.observability.RequestMetricsMiddleware',
            'greatkartecommerce.rate_limit.RateLimitMiddleware',
            'django.contrib.sessions.middleware.SessionMiddleware',
            'django.middleware.common.CommonMiddleware',
            'django.middleware.csrf.CsrfViewMiddleware',
            'django.contrib.auth.middleware.AuthenticationMiddleware',
            'django.contrib.messages.middleware.MessageMiddleware',
            'django.middleware.clickjacking.XFrameOptionsMiddleware',
            'django_session_timeout.middleware.SessionTimeoutMiddleware', # session timeout middleware

        ]

        SESSION_EXPIRE_SECONDS = 3600  # Session timeout in seconds (e.g., 60 seconds = 1 minute)
        SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True # Expire session after last activity
        SESSION_TIMEOUT_REDIRECT = 'accounts/login'  # Redirect to login page after timeout

        ROOT_URLCONF = 'greatkartecommerce.urls'

        TEMPLATES = [
            {
                'BACKEND': 'django.template.backends.django.DjangoTemplates',
                'DIRS': [BASE_DIR / 'templates'],  # Add your templates directory here
                'APP_DIRS': True,
                'OPTIONS': {
                    'context_processors': [
                        'django.template.context_processors.debug',
                        'django.template.context_processors.request',
                        'django.contrib.auth.context_processors.auth',
                        'django.contrib.messages.context_processors.messages',
                        'category.context_processors.menu_links',  # Add your custom context processor here
                        'carts.context_processors.counter',  # Add your custom context processor here
                        'wishlist.context_processors.wishlist_count',
                    ],
                },
            },
        ]

        WSGI_APPLICATION = 'greatkartecommerce.wsgi.application'

        AUTH_USER_MODEL = 'accounts.Account'    # Custom user model for authentication
        # https://docs.djangoproject.com/en/5.1/topics/auth/customizing/#specifying-a-custom-user-model


        # Database
        # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

        DB_ENGINE = config("DB_ENGINE", default="sqlite")
        if DB_ENGINE == "postgres":
            DATABASES = {
                "default": {
                    "ENGINE": "django.db.backends.postgresql",
                    "NAME": config("POSTGRES_DB"),
                    "USER": config("POSTGRES_USER"),
                    "PASSWORD": config("POSTGRES_PASSWORD"),
                    "HOST": config("POSTGRES_HOST", default="localhost"),
                    "PORT": config("POSTGRES_PORT", default=5432, cast=int),
                    "CONN_MAX_AGE": config("POSTGRES_CONN_MAX_AGE", default=60, cast=int),
                    "OPTIONS": {
                        "sslmode": config("POSTGRES_SSLMODE", default="prefer"),
                    },
                }
            }
        else:
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': BASE_DIR / 'db.sqlite3',
                }
            }


        # Password validation
        # https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

        AUTH_PASSWORD_VALIDATORS = [
            {
                'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
            },
            {
                'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
            },
            {
                'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
            },
            {
                'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
            },
        ]


        # Internationalization
        # https://docs.djangoproject.com/en/5.1/topics/i18n/

        LANGUAGE_CODE = 'en-us'

        TIME_ZONE = 'UTC'

        USE_I18N = True

        USE_TZ = True


        # Static files (CSS, JavaScript, Images)
        # https://docs.djangoproject.com/en/5.1/howto/static-files/

        STATIC_URL = 'static/'  # URL prefix for static files
        # Note: In development, you may want to use `python manage.py runserver` to serve static files automatically.
        STATICFILES_DIRS = [
              BASE_DIR / "greatkart/static",
              ]  # Add your static files directory here

        # Media files (e.g., uploaded files)
        MEDIA_URL = '/media/'
        MEDIA_ROOT = BASE_DIR / 'media'  # Directory where uploaded files will be stored
        CDN_DOMAIN = config("CDN_DOMAIN", default="")
        USE_S3_MEDIA = config("USE_S3_MEDIA", default=False, cast=bool)
        if CDN_DOMAIN:
            STATIC_URL = f"https://{CDN_DOMAIN}/static/"
            MEDIA_URL = f"https://{CDN_DOMAIN}/media/"
        if USE_S3_MEDIA:
            AWS_STORAGE_BUCKET_NAME = config("AWS_STORAGE_BUCKET_NAME")
            AWS_S3_REGION_NAME = config("AWS_S3_REGION_NAME", default="us-east-1")
            AWS_QUERYSTRING_AUTH = False
            AWS_DEFAULT_ACL = None
            AWS_S3_CUSTOM_DOMAIN = config("AWS_S3_CUSTOM_DOMAIN", default=f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com")
            MEDIA_URL = f"https://{AWS_S3_CUSTOM_DOMAIN}/media/"


        

        # Default primary key field type
        # https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

        DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

        MESSAGE_TAGS = {
            messages.ERROR: 'danger',
        }

        # Email configuration
        EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')
        EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
        EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)  # Use 587 for TLS
        EMAIL_HOST_USER = config('EMAIL_HOST_USER')
        EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
        EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)  # Use TLS instead of SSL
        EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)  # Ensure SSL is disabled

        # Fallback email backend for development
        if DEBUG:
            EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

        SITE_URL = config('SITE_URL', default='http://localhost:8000')
        INVENTORY_ALERT_EMAIL_RATE_LIMIT = config('INVENTORY_ALERT_EMAIL_RATE_LIMIT', default=1000, cast=int)

        # Redis cache/session configuration.
        REDIS_URL = config("REDIS_URL", default="redis://127.0.0.1:6379/1")
        CACHE_BACKEND = config("CACHE_BACKEND", default="locmem")
        if CACHE_BACKEND == "redis":
            CACHES = {
                "default": {
                    "BACKEND": "django_redis.cache.RedisCache",
                    "LOCATION": REDIS_URL,
                    "OPTIONS": {
                        "CLIENT_CLASS": "django_redis.client.DefaultClient",
                    },
                    "KEY_PREFIX": "greatkart",
                }
            }
            SESSION_ENGINE = "django.contrib.sessions.backends.cache"
            SESSION_CACHE_ALIAS = "default"
        else:
            CACHES = {
                "default": {
                    "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                    "LOCATION": "greatkart-local-cache",
                }
            }

        # Celery with Redis broker/result backend for worker + scheduler.
        CELERY_BROKER_URL = config("CELERY_BROKER_URL", default=REDIS_URL)
        CELERY_RESULT_BACKEND = config("CELERY_RESULT_BACKEND", default=REDIS_URL)
        CELERY_TASK_ALWAYS_EAGER = config("CELERY_TASK_ALWAYS_EAGER", default=False, cast=bool)
        CELERY_TASK_TIME_LIMIT = config("CELERY_TASK_TIME_LIMIT", default=300, cast=int)
        CELERY_TASK_SOFT_TIME_LIMIT = config("CELERY_TASK_SOFT_TIME_LIMIT", default=240, cast=int)
        CELERY_BEAT_SCHEDULE = {
            "process-inventory-alerts": {
                "task": "inventory_alerts.tasks.process_inventory_alerts",
                "schedule": crontab(minute="*/5"),
            },
            "recommendations-warm-cache": {
                "task": "recommendations.tasks.warm_cache_for_popular_products",
                "schedule": crontab(minute=0, hour="*/2"),
            },
        }

        # Security headers and HTTPS controls for hardened runtime.
        SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
        SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=not DEBUG, cast=bool)
        SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=not DEBUG, cast=bool)
        CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=not DEBUG, cast=bool)
        SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=31536000, cast=int)
        SECURE_HSTS_INCLUDE_SUBDOMAINS = config("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=True, cast=bool)
        SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=True, cast=bool)
        SECURE_CONTENT_TYPE_NOSNIFF = True
        SECURE_REFERRER_POLICY = config("SECURE_REFERRER_POLICY", default="strict-origin-when-cross-origin")
        X_FRAME_OPTIONS = "DENY"
        RATE_LIMIT_ENABLED = config("RATE_LIMIT_ENABLED", default=not DEBUG, cast=bool)
        RATE_LIMIT_WINDOW_SECONDS = config("RATE_LIMIT_WINDOW_SECONDS", default=60, cast=int)
        RATE_LIMIT_MAX_REQUESTS = config("RATE_LIMIT_MAX_REQUESTS", default=120, cast=int)
        RATE_LIMIT_PROTECTED_PREFIXES = (
            "/accounts/",
            "/orders/",
            "/cart/",
            "/checkout/",
            "/api/",
        )

        # Structured logging for centralized log ingestion.
        LOG_LEVEL = config("LOG_LEVEL", default="INFO")
        LOGGING = {
            "version": 1,
            "disable_existing_loggers": False,
            "formatters": {
                "json": {
                    "format": (
                        '{"timestamp":"%(asctime)s","level":"%(levelname)s",'
                        '"logger":"%(name)s","message":"%(message)s",'
                        '"path":"%(path)s","method":"%(method)s","status_code":"%(status_code)s",'
                        '"duration_ms":"%(duration_ms)s","user_id":"%(user_id)s"}'
                    ),
                },
                "default": {
                    "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
                },
            },
            "handlers": {
                "console": {
                    "class": "logging.StreamHandler",
                    "formatter": "default",
                    "level": LOG_LEVEL,
                },
                "json_console": {
                    "class": "logging.StreamHandler",
                    "formatter": "json",
                    "level": LOG_LEVEL,
                },
            },
            "loggers": {
                "greatkart.request": {
                    "handlers": ["json_console"],
                    "level": LOG_LEVEL,
                    "propagate": False,
                },
                "django": {
                    "handlers": ["console"],
                    "level": LOG_LEVEL,
                    "propagate": True,
                },
            },
        }

        if sentry_sdk:
            SENTRY_DSN = config("SENTRY_DSN", default="")
            SENTRY_TRACES_SAMPLE_RATE = config("SENTRY_TRACES_SAMPLE_RATE", default=0.1, cast=float)
            SENTRY_PROFILES_SAMPLE_RATE = config("SENTRY_PROFILES_SAMPLE_RATE", default=0.0, cast=float)
            if SENTRY_DSN:
                sentry_sdk.init(
                    dsn=SENTRY_DSN,
                    integrations=[DjangoIntegration()] if DjangoIntegration else [],
                    traces_sample_rate=SENTRY_TRACES_SAMPLE_RATE,
                    profiles_sample_rate=SENTRY_PROFILES_SAMPLE_RATE,
                    environment=config("SENTRY_ENVIRONMENT", default="dev"),
                    send_default_pii=False,
                )

        if os.environ.get('SILENCE_IMAGEFIELD_CHECKS') == '1':
            SILENCED_SYSTEM_CHECKS = ['fields.E210']


class Prod(Dev):
    """
    Production settings
    """
    DEBUG = values.BooleanValue(False)  # Set to True for development, False for production
    SECRET_KEY = values.SecretValue()
