# Generated by Django 5.1.7 on 2026-06-01 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comparison", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="savedcomparison",
            new_name="comparison__user_id_e874b7_idx",
            old_name="comparison_user_id_0abb31_idx",
        ),
        migrations.RenameIndex(
            model_name="savedcomparison",
            new_name="comparison__session_b6f7c5_idx",
            old_name="comparison_session_39f729_idx",
        ),
    ]
