# Generated by Django 5.1.7 on 2026-06-01 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="recommendationclick",
            new_name="recommendat_source__5091dd_idx",
            old_name="recommendat_source__e8f8a5_idx",
        ),
        migrations.RenameIndex(
            model_name="recommendationclick",
            new_name="recommendat_user_id_cfd7b6_idx",
            old_name="recommendat_user_id_a5e8f5_idx",
        ),
        migrations.RenameIndex(
            model_name="recommendationclick",
            new_name="recommendat_recomme_0b2307_idx",
            old_name="recommendat_recomme_b8f8a5_idx",
        ),
        migrations.RenameIndex(
            model_name="relatedproduct",
            new_name="related_pro_product_a8bd03_idx",
            old_name="related_pro_product_c8e8e5_idx",
        ),
    ]
